"""Render all specs into a consolidated markdown document."""

from pathlib import Path

import yaml
from rich.console import Console

from evospec.core.config import find_project_root, load_config, get_paths

console = Console()


def render_specs(include_archived: bool = False) -> None:
    """Render all specs into a single consolidated markdown file."""
    root = find_project_root()
    if root is None:
        console.print("[red]✗ No evospec.yaml found. Run `evospec init` first.[/red]")
        return

    config = load_config(root)
    paths = get_paths(config)
    specs_root = root / paths["specs"]
    adrs_root = root / paths["adrs"]
    domain_root = root / paths["domain"]

    output_lines: list[str] = []
    project_name = config.get("project", {}).get("name", "Project")

    output_lines.append(f"# {project_name} — EvoSpec Overview\n")
    output_lines.append(f"> Generated by `evospec render`\n\n")
    output_lines.append("---\n\n")

    # Domain section
    if domain_root.exists():
        output_lines.append("## Domain Model\n\n")
        for md_file in sorted(domain_root.glob("*.md")):
            content = md_file.read_text().strip()
            if content:
                output_lines.append(f"{content}\n\n---\n\n")

    # Specs section
    if specs_root.exists():
        spec_dirs = sorted(
            [d for d in specs_root.iterdir() if d.is_dir() and (d / "spec.yaml").exists()]
        )
        # Include archived specs if requested
        archive_root = root / "specs" / "archive"
        if include_archived and archive_root.exists():
            spec_dirs.extend(sorted(
                [d for d in archive_root.iterdir() if d.is_dir() and (d / "spec.yaml").exists()]
            ))

        if spec_dirs:
            output_lines.append("## Change Specifications\n\n")

            # Summary table
            output_lines.append("| Spec | Zone | Status | Risk |\n")
            output_lines.append("|------|------|--------|------|\n")
            for spec_dir in spec_dirs:
                with open(spec_dir / "spec.yaml") as f:
                    spec = yaml.safe_load(f) or {}
                title = spec.get("title", spec_dir.name)
                zone = spec.get("zone", "?")
                status = spec.get("status", "?")
                risk = spec.get("classification", {}).get("risk_level", "?")
                output_lines.append(f"| {title} | {zone} | {status} | {risk} |\n")

            output_lines.append("\n---\n\n")

            # Individual specs
            for spec_dir in spec_dirs:
                with open(spec_dir / "spec.yaml") as f:
                    spec = yaml.safe_load(f) or {}

                title = spec.get("title", spec_dir.name)
                output_lines.append(f"### {title}\n\n")

                # Include discovery spec if present
                discovery_path = spec_dir / "discovery-spec.md"
                if discovery_path.exists():
                    content = discovery_path.read_text().strip()
                    output_lines.append(f"{content}\n\n")

                # Include domain contract if present
                contract_path = spec_dir / "domain-contract.md"
                if contract_path.exists():
                    content = contract_path.read_text().strip()
                    output_lines.append(f"{content}\n\n")

                output_lines.append("---\n\n")

    # ADRs section
    if adrs_root.exists():
        adr_files = sorted(adrs_root.glob("*.md"))
        if adr_files:
            output_lines.append("## Architecture Decision Records\n\n")
            for adr_file in adr_files:
                content = adr_file.read_text().strip()
                output_lines.append(f"{content}\n\n---\n\n")

    # Write output
    output_path = root / "SPECS.md"
    output_path.write_text("".join(output_lines))

    spec_count = len([d for d in specs_root.iterdir() if d.is_dir()] if specs_root.exists() else [])
    console.print(f"[bold green]✓ Rendered to {output_path.relative_to(root)}[/bold green]")
    console.print(f"  Includes {spec_count} spec(s)")
    archive_root = root / "specs" / "archive"
    if not include_archived and archive_root.exists():
        archive_count = sum(1 for d in archive_root.iterdir() if d.is_dir() and (d / "spec.yaml").exists())
        if archive_count > 0:
            console.print(f"[dim]  {archive_count} archived spec(s) not included — use --include-archived to add them[/dim]")
